name: Update App Version
on:
  push:
    branches:
      - develop
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Set identity
        run: |
          git config --global user.name 'Gifa Eriyanto'
          git config --global user.email 'gifa.eriyanto@gmail.com'
      - name: Upgrade version
        run: yarn version --patch
      - name: Push update
        run: |
          git push origin develop
