name: Update App Version
on:
  push:
    branches:
      - develop
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Set identity
        run: |
          git config --global user.name 'Gifa Eriyanto'
          git config --global user.email 'gifa.eriyanto@gmail.com'
      - name: Upgrade version
        run: yarn version --patch
      - name: Commit update
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "chore: update version patch"
          git push origin develop
