name: Update App Version
on:
  push:
    branches:
      - develop

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/develop') && startsWith(github.event.head_commit.message, 'feat:')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Set identity
        run: |
          git config --global user.name 'Gifa Eriyanto'
          git config --global user.email 'gifa.eriyanto@gmail.com'
      - name: Upgrade version
        run: yarn version --patch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: develop
